NETWORK_NAME: "dockeranon_net"
NETWORK_RANGE: "192.168.5.0/24"
GATEWAY_NAME: "dockeranon_gateway"
GATEWAY_IP: "192.168.5.254"
GATEWAY_HOSTNAME: "gateway"
WORKSTATION_IMAGE: "jychp/xubuntu:latest"
WORKSTATION_NAME: "dockeranon_workstation"
WORKSTATION_IP: "192.168.5.10"
WORKSTATION_RESOLUTION: "1600x1024"
WORKSTATION_PASSWD: "password"
WORKSTATION_APPS: ""
WORKSTATION_HOSTNAME: "ubuntu"
VNC_CLIENT: "/usr/bin/vncviewer"
MOUNT_POINT: "/dev/shm/dockeranon"
MOUNT_POINT_USE: true